/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ArtistasIndexRouteImport } from './routes/artistas.index'
import { Route as ArtistasSlugRouteImport } from './routes/artistas.$slug'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasIndexRoute = ArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasSlugRoute = ArtistasSlugRouteImport.update({
  id: '/artistas/$slug',
  path: '/artistas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/lancamentos': typeof LancamentosRoute
  '/radar': typeof RadarRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/lancamentos': typeof LancamentosRoute
  '/radar': typeof RadarRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artistas': typeof ArtistasIndexRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/lancamentos': typeof LancamentosRoute
  '/radar': typeof RadarRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/lancamentos'
    | '/radar'
    | '/artistas/$slug'
    | '/noticias/$slug'
    | '/artistas/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/lancamentos'
    | '/radar'
    | '/artistas/$slug'
    | '/noticias/$slug'
    | '/artistas'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/anuncie'
    | '/lancamentos'
    | '/radar'
    | '/artistas/$slug'
    | '/noticias/$slug'
    | '/artistas/'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  LancamentosRoute: typeof LancamentosRoute
  RadarRoute: typeof RadarRoute
  ArtistasSlugRoute: typeof ArtistasSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ArtistasIndexRoute: typeof ArtistasIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/': {
      id: '/artistas/'
      path: '/artistas'
      fullPath: '/artistas/'
      preLoaderRoute: typeof ArtistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$slug': {
      id: '/artistas/$slug'
      path: '/artistas/$slug'
      fullPath: '/artistas/$slug'
      preLoaderRoute: typeof ArtistasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  LancamentosRoute: LancamentosRoute,
  RadarRoute: RadarRoute,
  ArtistasSlugRoute: ArtistasSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ArtistasIndexRoute: ArtistasIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
